### ISSUE TITLE
Get npm link working with Firebase app

### ISSUE THREAD

**Issue by tamsingreen** [bbc/digital-paper-edit-storybook#72]
**Describe the bug**
When the local copy of storybook is npm linked to firebase, the firebase app errors:
```Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

**Why it matters**
We need to test changes to [storybook](https://github.com/bbc/digital-paper-edit-storybook) within [firebase](https://github.com/bbc/digital-paper-edit-firebase) locally before publishing the storybook module to NPM.

**To Reproduce**
Steps to reproduce the behaviour (assuming you have both repos downloaded and dependencies installed) - following steps in https://github.com/bbc/digital-paper-edit-firebase/blob/master/docs/guides/npm-link.md:
1. In the storybook directory, run `npm run linked`
2. In another terminal window in the storybook dir, cd into dist then `npm link`
3. In the firebase directory, run `npm link @bbc/digital-paper-edit-storybook`
4. In the same directory, run `npm start`
5. The browser window briefly shows the login window before the error message as above.

**Expected behaviour**
The firebase app runs as expected and changes to the storybook components are reflected in the firebase app.

**Comment by jamesdools** [comment]
I ran the above and it worked for me.
It did give some warnings about dependencies missing in the output of `npm link` - but when running firebase with the linked package it didn't have those above errors 🤔 


I had to make sure to clear out the node_modules after the link, and run `npm unlink @bbc/digital-paper-edit-storybook` within the firebase repo first, because I had created a link for storybook's main directory, not the dist.

For the storybook repo:
I just put `react-dom` back into dependencies in storybook and also `$` char at the end of the regex in `webpack.dev.config.js` (Line 67)

**Comment by niklasR** [comment]
Just went through this with @tamsingreen and got it working by
- remove `react`, `react-dom` and `react-router` from the `dependencies` in `digital-paper-edit-storybook` before it all; also making sure the package-lock is up to date with that. These remain as peerDependencies, which will be fulfilled by the firebase repo:
  ```$ npm rm react react-dom react-router```
- install `babel-preset-minify` in `digital-paper-edit-storybook`:
    ```$ npm i babel-preset-minify ```
- follow steps as above

**Comment by emettely** [comment]
It looks like I've made some changes...:
- updated Webpack - meaning the `$` is now required for regex matching?
- refactored and added back in dependencies only required for the storybook

... since I've created that guide, and haven't reflected back to the doc, which meant that the dev config no longer worked.

As mentioned above by @jamesdools , you'll need to do this change:
https://github.com/bbc/digital-paper-edit-storybook/commit/b94245832e11ac7490f030d675f33d84320cfcf8

and you'll need to have removed the dependencies:
https://github.com/bbc/digital-paper-edit-storybook/commit/e8c4ef4758bd80aaf71f62cebf67fe8e1e645ba7#diff-7ae45ad102eab3b6d[…]470d7bc6507b6481575d519

**Comment by tamsingreen** [comment]
I'm working through getting this to run storybook locally (`npm run start`) as it needs those deps 🤔

**Comment by tamsingreen** [comment]
Testers couldn't get the PR solution to work, so moving this to the backlog again.

Another possible approach we could try: https://github.com/bbc/iplayer-web-components#locally-developing-with-web-applications
